# GENERATED by New-Importer — do not edit by hand. Regenerate with: New-Importer -RepositoryRoot <root>
#
# This shim carries only the importer's outer parameter form and delegates the whole load sequence to
# Invoke-Importer in automation/.internal/Catzc.Internal.Importer.psm1 (the single living copy). It is
# dot-sourced (. ./importer.ps1), so its $global:/$env: effects land in the caller's session.
param(
    [switch] $ExportPrivates,
    [switch] $AllowWarnings,
    [switch] $DiagnoseLoadTime,
    [switch] $ClearCompiledTypes,
    [switch] $NonSilentClear,
    [switch] $SkipJanitors,
    [switch] $NoCommitTriggersInDevBox
)

Set-StrictMode -Version Latest

# Repository root reference — the one path the shim anchors; the toolset reads it from $env:RepositoryRoot.
$env:RepositoryRoot = $PSScriptRoot

# Load the .internal shared-code loader (the one module imported by path), then the importer overlay, and
# delegate. Catzc.Internal.Importer is import-time orchestration — remove it once the load returns.
Import-Module (Join-Path $PSScriptRoot 'automation/.internal/Catzc.Internal.Loader.psm1') -Scope Global -Force
Import-InternalModule Importer -Force
try {
    Invoke-Importer @PSBoundParameters
}
finally {
    Remove-Module Catzc.Internal.Importer -Force -ErrorAction SilentlyContinue
}
