# foundation, apex nonprod subscription (env nsub, customer apex).
ParametersFile:
  parameters:
    logAnalyticsName:
      value: nsub-weu-zct-fnd-apex-log
    keyVaultName:
      value: ns-weu-zct-fnd-ap-kv
