# foundation, apex prod subscription (env psub, customer apex).
ParametersFile:
  parameters:
    logAnalyticsName:
      value: psub-weu-zct-fnd-apex-log
    keyVaultName:
      value: sp-weu-zct-fnd-ap-kv
