<#
.SYNOPSIS
    (Re)generates a repository's importer.ps1 shim from the Invoke-Importer overlay.
.DESCRIPTION
    importer.ps1 is a thin, generated entry point: it carries the importer's public parameter form and
    delegates the whole load sequence to Invoke-Importer (automation/.internal/Catzc.Internal.Importer.psm1),
    the single living copy. This reads the overlay's parameter block straight from that module's source (an AST
    parse — the overlay is not loaded post-import) and renders the shim around a fixed template, so the shim's
    parameters can never drift from the overlay's. A drift test asserts the committed importer.ps1 equals this
    output.

    Scaffolds into ANY repository root that already carries the .internal overlay — the loader path in the shim
    is repository-root-relative, so nothing absolute is baked in.
.PARAMETER RepositoryRoot
    The repository root to generate importer.ps1 into (and whose overlay is read). Defaults to this repository.
.PARAMETER Force
    Overwrite an existing importer.ps1. Without it, an existing importer.ps1 is left untouched (throws).
.PARAMETER DryRun
    Return the generated shim content as a string without writing anything.
.OUTPUTS
    [string] The generated content (-DryRun), otherwise the written importer.ps1 path.
.EXAMPLE
    New-Importer -Force
.EXAMPLE
    New-Importer -RepositoryRoot ./some/other/repo
#>
function New-Importer {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [string] $RepositoryRoot = (Get-RepositoryRoot),

        [switch] $Force,

        [switch] $DryRun
    )

    $overlayPath = Join-Path $RepositoryRoot 'automation/.internal/Catzc.Internal.Importer.psm1'
    if (-not (Test-Path -LiteralPath $overlayPath -PathType Leaf)) {
        throw "New-Importer: overlay not found at '$overlayPath' — the repository must carry the .internal toolset first."
    }

    # Read the overlay's parameter block from source (the overlay is not loaded post-import). Each parameter
    # becomes one clean `[type] $Name` line; the overlay keeps its own per-parameter doc comments.
    $parseErrors = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($overlayPath, [ref] $null, [ref] $parseErrors)
    if ($parseErrors) {
        throw "New-Importer: cannot parse overlay '$overlayPath':`n$(($parseErrors | ForEach-Object { $_.Message }) -join "`n")"
    }
    $overlay = $ast.Find({
            param($node)
            $node -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $node.Name -eq 'Invoke-Importer'
        }, $true)
    if (-not $overlay -or -not $overlay.Body.ParamBlock) {
        throw "New-Importer: overlay '$overlayPath' does not define Invoke-Importer with a param block."
    }

    $paramLines = foreach ($parameter in $overlay.Body.ParamBlock.Parameters) {
        $typeConstraint = $parameter.Attributes |
            Where-Object { $_ -is [System.Management.Automation.Language.TypeConstraintAst] } |
            Select-Object -First 1
        $typeText = if ($typeConstraint) {
            $typeConstraint.TypeName.Name
        }
        else {
            'object'
        }
        "    [$typeText] `$$($parameter.Name.VariablePath.UserPath)"
    }
    $paramBlock = "param(`n" + ($paramLines -join ",`n") + "`n)"

    # Fixed template around the generated param block. Single-quoted here-strings keep $env:/$PSScriptRoot/
    # @PSBoundParameters literal. The one living copy of the shim body lives here; importer.ps1 is generated.
    $header = @'
# GENERATED by New-Importer — do not edit by hand. Regenerate with: New-Importer -RepositoryRoot <root>
#
# This shim carries only the importer's outer parameter form and delegates the whole load sequence to
# Invoke-Importer in automation/.internal/Catzc.Internal.Importer.psm1 (the single living copy). It is
# dot-sourced (. ./importer.ps1), so its $global:/$env: effects land in the caller's session.
'@

    $body = @'
Set-StrictMode -Version Latest

# Repository root reference — the one path the shim anchors; the toolset reads it from $env:RepositoryRoot.
$env:RepositoryRoot = $PSScriptRoot

# Load the .internal shared-code loader (the one module imported by path), then the importer overlay, and
# delegate. Catzc.Internal.Importer is import-time orchestration — remove it once the load returns.
Import-Module (Join-Path $PSScriptRoot 'automation/.internal/Catzc.Internal.Loader.psm1') -Scope Global -Force
Import-InternalModule Importer -Force
try {
    Invoke-Importer @PSBoundParameters
}
finally {
    Remove-Module Catzc.Internal.Importer -Force -ErrorAction SilentlyContinue
}
'@

    # LF throughout, one trailing newline. The header/param/body join and the EOF newline match the committed
    # importer.ps1 byte-for-byte (the drift test compares EOL-insensitively).
    $content = $header + "`n" + $paramBlock + "`n`n" + $body + "`n"

    if ($DryRun) {
        return $content
    }

    $target = Join-Path $RepositoryRoot 'importer.ps1'
    if ((Test-Path -LiteralPath $target -PathType Leaf) -and -not $Force) {
        throw "New-Importer: '$target' already exists — pass -Force to overwrite."
    }
    [System.IO.File]::WriteAllText($target, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Message "Generated $target"
    $target
}
