name: catzc-base-environment
description: Derived module scope - automation/Catzc.Base.Environment/**
layer: module
include:
- 'automation/Catzc.Base.Environment/**'
sha256: b77908c13bac32dee619dc2ce28fcb5f26b9f81d1aeb746ae1869b779ba9c880
