name: catzc-tooling-environment-live
description: Derived module aspect - automation/Catzc.Tooling.Environment [live]
layer: module
scan:
- '+ automation/Catzc.Tooling.Environment/*.ps1'
- '+ automation/Catzc.Tooling.Environment/private/**'
- '+ automation/Catzc.Tooling.Environment/types/**'
- '+ automation/Catzc.Tooling.Environment/configs/**'
sha256: fd4d5bf0492019c0db20b679d6c6000f87c474f2f2384187af56d3cf0efce508
