name: catzc-base-rootconfig
description: Derived module scope - automation/Catzc.Base.RootConfig/**
layer: module
include:
- 'automation/Catzc.Base.RootConfig/**'
sha256: a34196105016a374041c25bf0b7d332d956ba650c90cda88836d3499304f6aab
