name: catzc-base-config
description: Derived module scope - automation/Catzc.Base.Config/**
layer: module
include:
- 'automation/Catzc.Base.Config/**'
sha256: a4d4597524b88ae2ceda0ef95bccc9c4dc229ee43d3a54b189193e51fd64e11c
