name: catzc-base-config-live
description: Derived module aspect - automation/Catzc.Base.Config [live]
layer: module
scan:
- '+ automation/Catzc.Base.Config/*.ps1'
- '+ automation/Catzc.Base.Config/private/**'
- '+ automation/Catzc.Base.Config/types/**'
- '+ automation/Catzc.Base.Config/configs/**'
scoped_sha256: 5be585b3b872a96f87bfd248adb0a96934204d7d3d5916a33536a0f6e867a70b
sha256: 6b3d8f634b44a4333727ddd5ae0bbb2c998c15e0a511f86b94b3f1ae7edae93a
