scoped_sha256: bb529f60b669492aeec7d5fe66e05a8c1578674c5f684ddf186d51f3e33436cd
filtered_sha256: 1826c2fdbde2b2185e80ef29e05be2a0fc4a48be0e2b37a8acaf60e1c455bf1e
scan:
- '+ automation/Catzc.Base.Environment/**'
- '- automation/Catzc.Base.Environment/*.ps1'
- '- automation/Catzc.Base.Environment/private/**'
- '- automation/Catzc.Base.Environment/types/**'
- '- automation/Catzc.Base.Environment/configs/**'
included:
- automation/Catzc.Base.Environment/assets/Set-LocalPSModulePath.ps1
- automation/Catzc.Base.Environment/tests/Add-PermanentPath.Tests.ps1
- automation/Catzc.Base.Environment/tests/Remove-PermanentPath.Tests.ps1
- automation/Catzc.Base.Environment/tests/Sync-SessionPath.Tests.ps1
filtered:
- automation/Catzc.Base.Environment/Catzc.Base.Environment.psd1
- automation/Catzc.Base.Environment/README.md
