generated_at: 2026-07-07T01:45:11Z
scoped_sha256: e2ddffd277e95e6e95e2c10c01889f8ecf597457c7b46ff73b2f9dbf1b862322
filtered_sha256: 671292a08ca4fe4ae927b109e076638c93cf59ef443938a38d36fd245494a2a5
scan:
- '+ automation/Catzc.Base.Config/**'
- '- automation/Catzc.Base.Config/*.ps1'
- '- automation/Catzc.Base.Config/private/**'
- '- automation/Catzc.Base.Config/types/**'
- '- automation/Catzc.Base.Config/configs/**'
included:
- automation/Catzc.Base.Config/tests/Config-Conventions.Tests.ps1
- automation/Catzc.Base.Config/tests/Get-Config.Tests.ps1
- automation/Catzc.Base.Config/tests/Get-ConfigValue.Tests.ps1
filtered:
- automation/Catzc.Base.Config/Catzc.Base.Config.psd1
- automation/Catzc.Base.Config/README.md
