name: catzc-base-environment-live
description: Derived module aspect - automation/Catzc.Base.Environment [live]
layer: module
scan:
- '+ automation/Catzc.Base.Environment/*.ps1'
- '+ automation/Catzc.Base.Environment/private/**'
- '+ automation/Catzc.Base.Environment/types/**'
- '+ automation/Catzc.Base.Environment/configs/**'
sha256: ea5241d2c7cf6d16e6e686e86b2f4a05e834ded7fb936c8b56b59a8a56ebd22a
