name: catzc-base-rootconfig
description: Derived module scope - automation/Catzc.Base.RootConfig/**
layer: module
scan:
- '+ automation/Catzc.Base.RootConfig/**'
sha256: 237b02b55ed8da0f97e21f2a92ceaed5999ab08851cb5d6253178138276e6c37
