generated_at: 2026-07-07T01:45:16Z
scoped_sha256: a5fcc5ace12faa8f45e9f12073a69cb6d4a84783e7e7a1897fb3e3ab0125e56f
filtered_sha256: a4c4ba685eb706524905183a9bb94f9a5932ff5dca660d01d1cbbf86488f6d4d
scan:
- '+ automation/Catzc.Tooling.Environment/**'
- '- automation/Catzc.Tooling.Environment/*.ps1'
- '- automation/Catzc.Tooling.Environment/private/**'
- '- automation/Catzc.Tooling.Environment/types/**'
- '- automation/Catzc.Tooling.Environment/configs/**'
included:
- automation/Catzc.Tooling.Environment/tests/Write-EnvironmentSet.Tests.ps1
filtered:
- automation/Catzc.Tooling.Environment/Catzc.Tooling.Environment.psd1
- automation/Catzc.Tooling.Environment/README.md
