<#
.SYNOPSIS
    Runs the test files through the parallel worker pool (and the serial phase) and aggregates the rows.
.DESCRIPTION
    Test-Automation's execution engine. Round-robins the parallel files across worker shards (generated by
    New-TestAutomationShardScript), runs them through the PesterRunner pool — live pooled output, at most
    one shard per worker slot — then runs the serial-tagged files in a final one-worker phase, alone.
    Aggregates every shard's rows-shard-<N>.json sidecar in shard order; a worker that exited outside {0,1}
    or never wrote its sidecar crashed before finishing, and the aggregation throws naming the shard rather
    than reporting a partial run as the whole truth.
.PARAMETER ParallelFiles
    The test files to shard across the pool (may be empty when only serial files are in scope).
.PARAMETER SerialFiles
    The serial-tagged test files for the final one-worker phase (may be empty).
.PARAMETER RunDirectory
    The run directory the shard scripts and their artifacts are written into.
.PARAMETER ExcludeTag
    Tags excluded from every worker's run (from Get-TestExcludeTag).
.PARAMETER Verbosity
    Pester output verbosity inside each worker.
.PARAMETER Workers
    Explicit pool size; 0 sizes automatically — max(1, ProcessorCount / 4), never more than the file count.
.PARAMETER TimeoutSeconds
    Hard ceiling per execution phase; on expiry the pool is killed and the run throws.
.PARAMETER WorkerEnvironment
    Extra environment variables for each worker's process (the L0/L1 tripwire) — never the parent's $env:.
.OUTPUTS
    [pscustomobject] with Rows (aggregated, in shard order), FailedShardLabels (shards that exited 1),
    ShardExitCodes (label -> exit code, for the run manifest), Shards (the shard descriptors, serial last),
    and DurationSeconds (wall clock across both phases).
#>
function Invoke-TestAutomationWorkers {
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param(
        [Parameter(Mandatory)]
        [AllowEmptyCollection()]
        [string[]] $ParallelFiles,

        [Parameter(Mandatory)]
        [AllowEmptyCollection()]
        [string[]] $SerialFiles,

        [Parameter(Mandatory)]
        [string] $RunDirectory,

        [AllowEmptyCollection()]
        [string[]] $ExcludeTag = @(),

        [ValidateSet('Minimal', 'Normal', 'Detailed', 'Diagnostic')]
        [string] $Verbosity = 'Detailed',

        [ValidateRange(0, 64)]
        [int] $Workers = 0,

        [ValidateRange(60, 86400)]
        [int] $TimeoutSeconds = 3600,

        [hashtable] $WorkerEnvironment
    )

    # Pool size: explicit -Workers, else ProcessorCount / 4 — measured on the full suite, wall clock is flat
    # from PC/4 up to PC/2 workers (the box saturates), while per-test wall clock inflates with every extra
    # worker until the level time limits read as breached. PC/4 keeps the timing report honest for free.
    # Never more workers than files, and at least one when only serial files exist (that pool is skipped below).
    $workerCount = if ($Workers -gt 0) {
        $Workers
    }
    else {
        [Math]::Max(1, [int][Math]::Floor([Environment]::ProcessorCount / 4))
    }
    $workerCount = [Math]::Max(1, [Math]::Min($workerCount, $ParallelFiles.Count))

    # Round-robin the parallel files across the shards — spreads the heavy modules; the serial phase (when
    # present) is one extra shard scheduled after the pool completes.
    $shardFiles = @{}
    for ($shardIndex = 0; $shardIndex -lt $workerCount; $shardIndex++) {
        $shardFiles[$shardIndex] = [System.Collections.Generic.List[string]]::new()
    }
    for ($fileIndex = 0; $fileIndex -lt $ParallelFiles.Count; $fileIndex++) {
        $shardFiles[$fileIndex % $workerCount].Add($ParallelFiles[$fileIndex])
    }

    $shards = [System.Collections.Generic.List[object]]::new()
    for ($shardIndex = 0; $shardIndex -lt $workerCount; $shardIndex++) {
        if ($shardFiles[$shardIndex].Count -eq 0) {
            continue
        }
        $shards.Add((New-TestAutomationShardScript -ShardIndex $shardIndex -TestPath $shardFiles[$shardIndex] `
                    -RunDirectory $RunDirectory -ExcludeTag $ExcludeTag -Verbosity $Verbosity))
    }
    $serialShard = $null
    if ($SerialFiles.Count -gt 0) {
        $serialShard = New-TestAutomationShardScript -ShardIndex $workerCount -TestPath $SerialFiles `
            -RunDirectory $RunDirectory -ExcludeTag $ExcludeTag -Verbosity $Verbosity
    }

    # Announce before the pool blocks: each worker pays its own importer + Pester load before the first
    # Pester line streams, so silence here would read as a hang (ADR-CONSOLE:10).
    Write-Message "Running $($ParallelFiles.Count) test file(s) across $($shards.Count) parallel worker(s)$(if ($serialShard) { ", then $($SerialFiles.Count) serial-tagged file(s)" })..." -NoHeader

    $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
    $workerResults = [System.Collections.Generic.List[object]]::new()
    $allShards = [System.Collections.Generic.List[object]]::new()

    if ($shards.Count -gt 0) {
        $runner = [Catzc.Base.QualityGates.PesterRunner]::Run(
            [string[]] @($shards.ScriptPath), [string[]] @($shards.Label), $shards.Count,
            $WorkerEnvironment, $TimeoutSeconds, $false)
        $workerResults.AddRange($runner.Results)
        $allShards.AddRange($shards)
    }

    # The serial phase runs after the pool, alone — its files mutate state the parallel workers must not see
    # changing underneath them.
    if ($serialShard) {
        Write-Message "Serial phase: $($SerialFiles.Count) serial-tagged file(s) in one worker..." -NoHeader
        $serialRunner = [Catzc.Base.QualityGates.PesterRunner]::Run(
            [string[]] @($serialShard.ScriptPath), [string[]] @($serialShard.Label), 1,
            $WorkerEnvironment, $TimeoutSeconds, $false)
        $workerResults.AddRange($serialRunner.Results)
        $allShards.Add($serialShard)
    }
    $stopwatch.Stop()

    # Aggregate the rows sidecars, in shard order. A worker that exited outside {0,1} or never wrote its
    # artifacts (the rows sidecar AND the NUnit results file — asserted here, not inferred from the shard
    # script's write order) crashed before finishing its run — fail loudly naming the shard and the run
    # directory rather than reporting a partial run as the whole truth. run.json in that directory carries
    # the run's own status record (see Write-TestRunManifest).
    $rows = [System.Collections.Generic.List[object]]::new()
    $failedShardLabels = [System.Collections.Generic.List[string]]::new()
    $shardExitCodes = [ordered]@{}
    for ($shardIndex = 0; $shardIndex -lt $allShards.Count; $shardIndex++) {
        $shard = $allShards[$shardIndex]
        $workerResult = $workerResults[$shardIndex]
        $shardExitCodes[$shard.Label] = $workerResult.ExitCode

        if ($workerResult.ExitCode -notin 0, 1 -or -not (Test-Path $shard.RowsPath) -or -not (Test-Path $shard.ResultsPath)) {
            $stderrTail = "$($workerResult.Stderr)".Trim()
            throw ("Test worker '$($shard.Label)' crashed (exit $($workerResult.ExitCode)) without completing its run" +
                " — see $RunDirectory (run.json carries the run status)." +
                $(if ($stderrTail) {
                        " Stderr:`n$stderrTail"
                    }))
        }
        if ($workerResult.ExitCode -eq 1) {
            $failedShardLabels.Add($shard.Label)
        }

        foreach ($row in @([System.IO.File]::ReadAllText($shard.RowsPath) | ConvertFrom-Json)) {
            $rows.Add($row)
        }
    }

    [pscustomobject]@{
        Rows              = @($rows)
        FailedShardLabels = @($failedShardLabels)
        ShardExitCodes    = $shardExitCodes
        Shards            = @($allShards)
        DurationSeconds   = $stopwatch.Elapsed.TotalSeconds
    }
}
